services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend
    environment:
      DB_SQL_SETTINGS__HOST: ${POSTGRES_HOST:-postgres}
      DB_SQL_SETTINGS__PORT: ${POSTGRES_PORT:-5432}
      DB_SQL_SETTINGS__USERNAME: ${POSTGRES_USER:-postgres}
      DB_SQL_SETTINGS__PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      DB_SQL_SETTINGS__DATABASE: ${POSTGRES_DB:-postgres}
    ports:
      - "8000:8000"
    depends_on:
      postgres:
        condition: service_healthy
    restart: always

  postgres:
    image: postgres:18-alpine
    hostname: postgres
    container_name: postgres
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-postgres}
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  postgres_data:
    driver: local
